name: Bug Fix
description: Create a pull request for a bug fix
labels: [bug]
 - type: checkboxes
    id: readable
    attributes:
      label: The code is readable ?
      description: If your code is readable (unlike transpiler).
      options:
        - label: Yes my code is readable.
          required: true
 - type: checkboxes
    id: tested
    attributes:
      label: The code get tested ?
      description: If you test your code.
      options:
        - label: Yes my code is tested.
          required: true
- type: textarea
    attributes:
      id: bugDescription
      label: Bug description or link to the github/discord issue.
      description: A clear description of the bug.
    validations:
      required: true
- type: textarea
    attributes:
      id: fixDescription
      label: Bug fix explained.
      description: A clear description of who you are fixing the bug.
    validations:
      required: false
- type: textarea
    attributes:
      label: Steps To Reproduce the bug and the test.
      description: Steps to reproduce the behavior.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
