namespace Synapse.Api.Enum
{
    public enum AmbientSound
    {// 
        PowerEngaged = 0,
        HeavyObjectFall = 1,
        Tile = 2,
        HeavyDoor = 3,
        LightSlipingObject = 4,
        Whale = 5,
        Scp079 = 6,
        InformaticBeep = 7,
        Circle = 8,
        RisingCiment = 9,
        Breath = 10,
        BigBreath = 11,
        HeavyBreath = 12,
        SmollBreath = 13,
        LitleBreath = 14,
        LongBreath = 15,
        LightWaher = 16,
        Crash = 17,
        MechanicalMovement = 18,
        Wind = 19,
        SlipingObject = 20,
        MultipleSmallBeep = 21,
        LongBeep = 22,
        AlertBeep = 23,
        AudibleLongBeep = 24,
        RisingAndFallingBeep = 25,
        WeakBeep = 26,
        Valve = 27,
        Thunderstorm = 28,
        OldHardDrive = 29,
        AudibleAlertBeep = 30,
        ComputerSound = 31,
    }
}
