name: Bug Fix
description: Create a pull request for a bug fix
labels: [bug]
 - type: checkboxes
    id: major
    attributes:
      label: Crash or unsyc::
      description: If the server crashes after the bug or if the player get unsync (the player cannot interact with the server but is still "connected")
      options:
        - label: Yes the server crash or player are unsyc
    validations:
      required: true
- type: textarea
    attributes:
      id: description
      label: Description::
      description: A clear description of the bug.
    validations:
      required: true
- type: textarea
    attributes:
      label: Steps To Reproduce the bug::
      description: Steps to reproduce the behavior.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
- type: textarea
    attributes:
      id: log
      label: Log::
      description: Output log when the bug occur.
    validations:
      required: false
