name: "Report a Bug"
description: Report errors or unexpected behavior
labels: [bug]
body:
- id: major
  type: checkboxes
  attributes:
    label: Crash or unsyc
    description: If the server crashes after the bug or if the player get unsync (the player cannot interact with the server but is still "connected")
    options:
      - label: Yes the server crash or player are unsyc
  validations:
    required: true

- id: version
  type: input
  attributes:
    label: Version
    placeholder: "3.0.0"
  validations:
    required: true

- id: description
  type: textarea
  attributes:
    label: Description
    description: A clear description of the bug.
  validations:
    required: true

- id: steps
  type: textarea
  attributes:
    label: Steps To Reproduce the bug
    description: Steps to reproduce the behavior.
    placeholder: |
      1.
      2.
      3.
  validations:
    required: true

- id: modules
  type: textarea
  attributes:
    label: Modules
    description: The list of the modules of the server
  validations:
    required: false

- id: plugins
  type: textarea
  attributes:
    label: Plugins
    description: The list of the plugins of the server
  validations:
    required: false

- id: log
  type: textarea
  attributes:
    label: Log
    description: Output log when the bug occur.
  validations:
    required: false
