name: Bug Fix
description: Create a pull request for a bug fix
labels: [bug]
- type: textarea
    attributes:
      id: description
      label: Description::
      description: A clear description of what is missing in documentation or what is wrong.
    validations:
      required: true
- type: textarea
    attributes:
      id: need
      label: What wanted us to do::
    validations:
      required: false
