name: "Ask for error/lack of documentation"
description: Report lack or miss information in the the doc
labels: [documentation, enhancement]
body:
- id: description
  type: textarea
    attributes:
      label: Description::
      description: A clear description of what is missing in documentation or what is wrong.
    validations:
      required: true

- id: need
  type: textarea
  attributes:
    label: What wanted us to do::
  validations:
    required: false
