name: "Requestion a new translation"
description: Ask for a new translation
labels: [No Priority, enhancement]
body:
- id: langage
  type: textarea
  attributes:
    label: Langage::
    placeholder: "French"
    validations:
    required: true
